server:
  port: 0
spring:
  application:
    name: starcourt-mall-stock
  jpa:
    hibernate:
      ddl-auto: none
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

