server:
  port: 0
spring:
  application:
    name: starcourt-stock
  datasource:
    url: jdbc:mysql://localhost:3306/starcourt_stock?characterEncoding=utf8
    username: root
    password: ''
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

