server:
  port: 0
spring:
  application:
    name: starcourt-mall-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
zuul:
  ignoredServices: '*'
  routes:
    catalog:
      path: /catalog/**
      strip-prefix: true
      service-id: starcourt-mall-catalog
    stock:
      path: /stock/**
      strip-prefix: true
      service-id: starcourt-mall-stock
    review:
      path: /review/**
      strip-prefix: true
      service-id: starcourt-mall-review
