server:
  port: 8080
spring:
  application:
    name: starcourt-mall-storefront
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
starcourt-mall-gateway:
  ribbon:
    eureka:
      enabled: true
